services:
  - type: web
    name: entrenaments
    env: node
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
